// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqWIIhzwJNobrpijD8j0ji28f1WuvtpWI',
    appId: '1:778766105232:web:f8068864c6176c232bf615',
    messagingSenderId: '778766105232',
    projectId: 'ejemplo-fef6e',
    authDomain: 'ejemplo-fef6e.firebaseapp.com',
    storageBucket: 'ejemplo-fef6e.firebasestorage.app',
    measurementId: 'G-CLW0RWLW1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzaRvq6Qxj5RgyJFs0booi9rlFFPO7P7w',
    appId: '1:778766105232:android:ce4b0b25e8e6baa92bf615',
    messagingSenderId: '778766105232',
    projectId: 'ejemplo-fef6e',
    storageBucket: 'ejemplo-fef6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB261OtmfvVeQdcpauHPk3s1UDQQAOdPmY',
    appId: '1:778766105232:ios:50b74599e013ce042bf615',
    messagingSenderId: '778766105232',
    projectId: 'ejemplo-fef6e',
    storageBucket: 'ejemplo-fef6e.firebasestorage.app',
    iosBundleId: 'com.example.tienda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB261OtmfvVeQdcpauHPk3s1UDQQAOdPmY',
    appId: '1:778766105232:ios:50b74599e013ce042bf615',
    messagingSenderId: '778766105232',
    projectId: 'ejemplo-fef6e',
    storageBucket: 'ejemplo-fef6e.firebasestorage.app',
    iosBundleId: 'com.example.tienda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqWIIhzwJNobrpijD8j0ji28f1WuvtpWI',
    appId: '1:778766105232:web:66e3fcf090593d142bf615',
    messagingSenderId: '778766105232',
    projectId: 'ejemplo-fef6e',
    authDomain: 'ejemplo-fef6e.firebaseapp.com',
    storageBucket: 'ejemplo-fef6e.firebasestorage.app',
    measurementId: 'G-6MFC886339',
  );

}